services:
  api: 
    image: gopenux/flask-docker-swarm:latest
    environment:
      DB_URL: "mongodb://database-network:27017/mydb"
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - network-db
      - network-nginx
    deploy:
      replicas: 1
 

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - ./dbmongo:/data/db  
    networks:
      network-db:  
        aliases:
          - database-network

  ingress:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/ssl
    networks:
      network-nginx:
        aliases:
          - nginx-network 

networks:
  network-db:
    driver: overlay  
  network-nginx:
    driver: overlay  

