services:
  api: 
    image: danielsanchez18/gopenux-flask-docker-swarm:v1
    environment:
      DB_URL: "mongodb://database:27017/mydb"
    ports:
      - "5000:5000"
    networks:
      network-db:
        aliases:
          - api-network
      network-nginx:
        aliases:
          - api
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - ./dbmongo:/data/db  
    networks:
      network-db:  
        aliases:
          - database-network
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager

  ingress:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /nginx/certs:/etc/nginx/ssl
    networks:
      network-nginx:
        aliases:
          - nginx-network 
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == worker

networks:
  network-db:
    driver: overlay  
  network-nginx:
    driver: overlay  